### ISSUE TITLE
No checkpoint found at 'models/reid_checkpoint.pth.tar'

### ISSUE THREAD

**Issue by zhangwengyu999** [zekunqian/BEVSee#2]
Hi! Thank you very much for the amazing work!

After I run the `python train.py`, it gives the error 

```
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    train_monoreid_net_with_xy_and_r(cfg)
  File "/home/xxx/work/BEVSee/train_net.py", line 216, in train_monoreid_net_with_xy_and_r
    model_reid = reidnet.reidnet()
  File "/home/xxx/work/BEVSee/nets/reidnet.py", line 19, in __init__
    checkpoint = load_checkpoint('models/reid_checkpoint.pth.tar')
  File "/home/xxx/work/BEVSee/reid/utils/serialization.py", line 23, in load_checkpoint
    raise ValueError("=> No checkpoint found at '{}'".format(fpath))
ValueError: => No checkpoint found at 'models/reid_checkpoint.pth.tar'
```

The error comes from [Line 19 in nets/reidnet.py](https://github.com/zekunqian/BEVSee/blob/master/nets/reidnet.py#L19):

```python
checkpoint = load_checkpoint('models/reid_checkpoint.pth.tar')
```

and I can not find the `reid_checkpoint.pth.tar` file in your provided cloud driver.

How to solve the problem?

Thank you very much!

**Comment by zekunqian** [comment]
Thank you for your attention to our work. I apologize for forgetting to upload the `checkpoint.pth.tar` file😅. The model has now been uploaded and should be available for download. I hope this hasn't caused any delay in your research. Best of luck with your research🌟!
